version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:0-20
    volumes:
      - .:/workspace
    working_dir: /workspace
    ports:
      - "3000:3000"
    command:  >
      sh -c "yarn install &&
            yarn dev &&
            sleep infinity"